/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as helpersSol from "./Helpers.sol";
export { MainPlatform__factory } from "./MainPlatform__factory";
export { Question__factory } from "./Question__factory";
