/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MainPlatform__factory } from "./MainPlatform__factory";
export { Question__factory } from "./Question__factory";
export { QuestionFrame__factory } from "./QuestionFrame__factory";
