/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "MainPlatform",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MainPlatform__factory>;
    getContractFactory(
      name: "Question",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Question__factory>;
    getContractFactory(
      name: "QuestionFrame",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.QuestionFrame__factory>;

    getContractAt(
      name: "MainPlatform",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MainPlatform>;
    getContractAt(
      name: "Question",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Question>;
    getContractAt(
      name: "QuestionFrame",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.QuestionFrame>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
