/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as helpersSol from "./Helpers.sol";
export type { helpersSol };
export type { MainPlatform } from "./MainPlatform";
export type { Question } from "./Question";
export * as factories from "./factories";
export type { PlatformConfig } from "./Helpers.sol/PlatformConfig";
export { PlatformConfig__factory } from "./factories/Helpers.sol/PlatformConfig__factory";
export { MainPlatform__factory } from "./factories/MainPlatform__factory";
export { Question__factory } from "./factories/Question__factory";
