/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MainPlatform } from "./MainPlatform";
export type { Question } from "./Question";
export type { QuestionFrame } from "./QuestionFrame";
export * as factories from "./factories";
export { MainPlatform__factory } from "./factories/MainPlatform__factory";
export { Question__factory } from "./factories/Question__factory";
export { QuestionFrame__factory } from "./factories/QuestionFrame__factory";
