/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type QuestionMetaStruct = {
  owner: PromiseOrValue<string>;
  title: PromiseOrValue<string>;
  description: PromiseOrValue<string>;
  labels: PromiseOrValue<string>[];
  scores: PromiseOrValue<BigNumberish>[];
  extras: [
    PromiseOrValue<BigNumberish>,
    PromiseOrValue<BigNumberish>,
    PromiseOrValue<BigNumberish>
  ];
};

export type QuestionMetaStructOutput = [
  string,
  string,
  string,
  string[],
  BigNumber[],
  [BigNumber, BigNumber, BigNumber]
] & {
  owner: string;
  title: string;
  description: string;
  labels: string[];
  scores: BigNumber[];
  extras: [BigNumber, BigNumber, BigNumber];
};

export type QuestionInfoOutputStruct = {
  question: QuestionMetaStruct;
  totalVoters: PromiseOrValue<BigNumberish>;
  hasVoted: PromiseOrValue<boolean>;
};

export type QuestionInfoOutputStructOutput = [
  QuestionMetaStructOutput,
  BigNumber,
  boolean
] & {
  question: QuestionMetaStructOutput;
  totalVoters: BigNumber;
  hasVoted: boolean;
};

export interface MainPlatformInterface extends utils.Interface {
  functions: {
    "addQuestion(string,string[])": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "getAllQuestions()": FunctionFragment;
    "getQuestionInfo(uint256)": FunctionFragment;
    "isRegisteredUser()": FunctionFragment;
    "owner()": FunctionFragment;
    "register()": FunctionFragment;
    "totalQuestions()": FunctionFragment;
    "totalUsers()": FunctionFragment;
    "vote(uint256,uint256)": FunctionFragment;
    "voteExtra(uint256,uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addQuestion"
      | "balanceOf"
      | "getAllQuestions"
      | "getQuestionInfo"
      | "isRegisteredUser"
      | "owner"
      | "register"
      | "totalQuestions"
      | "totalUsers"
      | "vote"
      | "voteExtra"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addQuestion",
    values: [PromiseOrValue<string>, PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllQuestions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getQuestionInfo",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegisteredUser",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "register", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalQuestions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "voteExtra",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addQuestion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllQuestions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuestionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegisteredUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalQuestions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalUsers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voteExtra", data: BytesLike): Result;

  events: {};
}

export interface MainPlatform extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MainPlatformInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addQuestion(
      title: PromiseOrValue<string>,
      labels: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    balanceOf(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getAllQuestions(
      overrides?: CallOverrides
    ): Promise<[QuestionInfoOutputStructOutput[]]>;

    getQuestionInfo(
      questionID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[QuestionInfoOutputStructOutput]>;

    isRegisteredUser(overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    register(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    totalQuestions(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalUsers(overrides?: CallOverrides): Promise<[BigNumber]>;

    vote(
      questionID: PromiseOrValue<BigNumberish>,
      voteOption: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    voteExtra(
      questionID: PromiseOrValue<BigNumberish>,
      extraOption: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addQuestion(
    title: PromiseOrValue<string>,
    labels: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  balanceOf(
    _address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAllQuestions(
    overrides?: CallOverrides
  ): Promise<QuestionInfoOutputStructOutput[]>;

  getQuestionInfo(
    questionID: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<QuestionInfoOutputStructOutput>;

  isRegisteredUser(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  register(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  totalQuestions(overrides?: CallOverrides): Promise<BigNumber>;

  totalUsers(overrides?: CallOverrides): Promise<BigNumber>;

  vote(
    questionID: PromiseOrValue<BigNumberish>,
    voteOption: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  voteExtra(
    questionID: PromiseOrValue<BigNumberish>,
    extraOption: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addQuestion(
      title: PromiseOrValue<string>,
      labels: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOf(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllQuestions(
      overrides?: CallOverrides
    ): Promise<QuestionInfoOutputStructOutput[]>;

    getQuestionInfo(
      questionID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<QuestionInfoOutputStructOutput>;

    isRegisteredUser(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    register(overrides?: CallOverrides): Promise<void>;

    totalQuestions(overrides?: CallOverrides): Promise<BigNumber>;

    totalUsers(overrides?: CallOverrides): Promise<BigNumber>;

    vote(
      questionID: PromiseOrValue<BigNumberish>,
      voteOption: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    voteExtra(
      questionID: PromiseOrValue<BigNumberish>,
      extraOption: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addQuestion(
      title: PromiseOrValue<string>,
      labels: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    balanceOf(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllQuestions(overrides?: CallOverrides): Promise<BigNumber>;

    getQuestionInfo(
      questionID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRegisteredUser(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    register(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    totalQuestions(overrides?: CallOverrides): Promise<BigNumber>;

    totalUsers(overrides?: CallOverrides): Promise<BigNumber>;

    vote(
      questionID: PromiseOrValue<BigNumberish>,
      voteOption: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    voteExtra(
      questionID: PromiseOrValue<BigNumberish>,
      extraOption: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addQuestion(
      title: PromiseOrValue<string>,
      labels: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    balanceOf(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllQuestions(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getQuestionInfo(
      questionID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isRegisteredUser(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    register(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    totalQuestions(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalUsers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vote(
      questionID: PromiseOrValue<BigNumberish>,
      voteOption: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    voteExtra(
      questionID: PromiseOrValue<BigNumberish>,
      extraOption: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
