/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type QuestionInfoStruct = {
  owner: PromiseOrValue<string>;
  title: PromiseOrValue<string>;
  description: PromiseOrValue<string>;
  labels: PromiseOrValue<string>[];
  scores: PromiseOrValue<BigNumberish>[];
  extras: [
    PromiseOrValue<BigNumberish>,
    PromiseOrValue<BigNumberish>,
    PromiseOrValue<BigNumberish>
  ];
  totalVoters: PromiseOrValue<BigNumberish>;
  hasVoted: PromiseOrValue<boolean>;
};

export type QuestionInfoStructOutput = [
  string,
  string,
  string,
  string[],
  BigNumber[],
  [BigNumber, BigNumber, BigNumber],
  BigNumber,
  boolean
] & {
  owner: string;
  title: string;
  description: string;
  labels: string[];
  scores: BigNumber[];
  extras: [BigNumber, BigNumber, BigNumber];
  totalVoters: BigNumber;
  hasVoted: boolean;
};

export interface QuestionFrameInterface extends utils.Interface {
  functions: {
    "accept(uint256)": FunctionFragment;
    "acceptExtra(uint8)": FunctionFragment;
    "editDescription(string)": FunctionFragment;
    "outputQuestionInfo()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "accept"
      | "acceptExtra"
      | "editDescription"
      | "outputQuestionInfo"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accept",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptExtra",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "editDescription",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "outputQuestionInfo",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "accept", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "acceptExtra",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "editDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "outputQuestionInfo",
    data: BytesLike
  ): Result;

  events: {};
}

export interface QuestionFrame extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: QuestionFrameInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accept(
      option: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    acceptExtra(
      option: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    editDescription(
      newDescription: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    outputQuestionInfo(
      overrides?: CallOverrides
    ): Promise<[QuestionInfoStructOutput]>;
  };

  accept(
    option: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  acceptExtra(
    option: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  editDescription(
    newDescription: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  outputQuestionInfo(
    overrides?: CallOverrides
  ): Promise<QuestionInfoStructOutput>;

  callStatic: {
    accept(
      option: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    acceptExtra(
      option: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    editDescription(
      newDescription: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    outputQuestionInfo(
      overrides?: CallOverrides
    ): Promise<QuestionInfoStructOutput>;
  };

  filters: {};

  estimateGas: {
    accept(
      option: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    acceptExtra(
      option: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    editDescription(
      newDescription: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    outputQuestionInfo(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    accept(
      option: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    acceptExtra(
      option: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    editDescription(
      newDescription: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    outputQuestionInfo(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
